version: '3.3'
services:
  # TODO: DBとの接続情報（DB_User,DB_PASS,DB_NAME）を環境変数で指定する必要がある
  # app:
  #   build: .
  #   container_name: blog-api
  #   depends_on:
  #     - mysql
  #   volumes:
  #     - ./:/go/src/app
  #   ports:
  #     - "8080:8080"
  #   tty: true

  mysql:
    platform: linux/x86_64 # M1Mac用
    image: mysql:5.7
    container_name: db-for-go

    # MySQLの設定値を指定
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --sql-mode=ONLY_FULL_GROUP_BY,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

    # コンテナ内で使用する環境変数の値を指定
    environment:
      MYSQL_ROOT_USER: ${ROOTUSER}
      MYSQL_ROOT_PASSWORD: ${ROOTPASS}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USERNAME}
      MYSQL_PASSWORD: ${USERPASS}
      TZ: 'Asia/Tokyo'

    # ホスト側のポートとコンテナ側のポートを紐付け
    ports:
      - "3306:3306"

    # コンテナ内にあるMYSQLに格納するデータを永続化させるために使用するボリュームを指定
    volumes:
      - db-volume:/var/lib/mysql

volumes:
  db-volume:
